### ISSUE TITLE
Empty datasets / queries return an ambiguous error

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#1049]
It returns `CartoMapsAPIError: SQL errors: ["Cannot read property 'geom_type' of undefined"]`

See https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiU0VMRUNUICogZnJvbSBzcGVuZF9kYXRhIFdIRVJFIGZhbHNlIiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJ3aWR0aDogN1xuY29sb3I6IHJnYigyMDQsMCwwKSIsImYiOnsibG5nIjoyLjE3LCJsYXQiOjQxLjM4fSwiZyI6MTMsImgiOiJEYXJrTWF0dGVyIiwiaSI6InF1ZXJ5In0=

**Comment by Captain-Oski** [comment]
Hello ! I am experiencing the same issue when trying to query a jsonb column. Query is straightforward but it returns no data and geom_type undefined. Query works in most postgresql environnements but here I have no luck and tried many different approaches.

see example

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoic2VsZWN0ICpcbmZyb20gICB0ZXN0XzFcbndoZXJlIGxpc3Rlc2VnIEA+ICdbe1wiaWRcIjogMTE1MDAwNH1dJyIsImIiOiIiLCJjIjoiYW5hZ3JhcGgtY2xlbWVudCIsImQiOiJodHRwczovL2FuYWdyYXBoLWNsZW1lbnQuY2FydG8uY29tIiwiZSI6IndpZHRoOiA3XG5jb2xvcjogcmdiKDIwNCwwLDApIiwiZiI6eyJsbmciOi03My4zOTc0MTk5MjM5NjUzNCwibGF0Ijo0NS41NTM3MjY5MzgzODgzNjV9LCJnIjo4Ljg3NTE5NTcxNDYzMTgyNCwiaCI6IkRhcmtNYXR0ZXIiLCJpIjoicXVlcnkifQ==

**Comment by davidmanzanares** [comment]
Hi,

Sorry for the late response.

The reason for that is that Maps API don't know how to encode JSON values in the MVT tiles. This can easily be fixed by casting the JSON column to `text` (`::text`) in the SQL query.

**Comment by rochoa** [comment]
This is not fixed yet. The changes in the Maps API are just the first step.
